### ISSUE TITLE
Selex for reference points should be weighted averages of F

### ISSUE THREAD

**Issue by chengmatt** [Ovec8hkin/SablefishMSE#2]
Selectivity used to compute reference points should be weighted by the terminal year fleet-specific Fs (lines 281 - 283 in PR) (i.e., (sel_hal * hal_f + sel_trwl * trwl_f) / max((sel_hal * hal_f + sel_trwl * trwl_f))).

**Comment by Ovec8hkin** [comment]
Fixed with 9ea8953
