### ISSUE TITLE
reshape2

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [Ovec8hkin/SablefishMSE#3]
https://github.com/Ovec8hkin/SablefishMSE/blob/9e2a8588e252f09c025f45237fde55c1d184cd10/R/data_processing.R#L2

`reshape2` is being used in a number of locations, this package has been retired and no longer supported, recommend changing to `tidyr::pivot_longer()`

**Comment by Ovec8hkin** [comment]
I am relying on `reshape2::melt` right now because it handles converting a multidimensional array into a long data.frame. What alternative packages do this? I can't find a tidyverse solution that accomplishes this easily.

**Comment by BenWilliams-NOAA** [comment]
yeah don't worry about it. thought `tidyr` could handle arrays as well. 
anyway, reshape2 isn't going away, it just isn't being updated anymore - that said it is possible to do the same things with `data.table::as.data.table()`

**Comment by Ovec8hkin** [comment]
Looks like this: `as_tibble(arr) %>% pivot_longer(everything(), names_sep="\\.", names_to=c("age", "sex", "region", "sim"))` also works

**Comment by BenWilliams-NOAA** [comment]
recommend leaving as is
