### ISSUE TITLE
Wrapper for running MSE sims cross multiple OMs and HCRs

### ISSUE THREAD

**Issue by Ovec8hkin** [Ovec8hkin/SablefishMSE#5]
There is currently a parallel wrapper function for running an MSE (with a specific OM and HCR combination) multiple times with different random seeds. This will need to be extended to work across multiple OMs, multiple HCRs, and multiple simulation seeds.

The way I handled this for the PWS MSE was to use `expand.grid` to create a factorial table with all combination of OMs, HCRs, and seeds, and then looped over that table in parallel, while parsing out the correct object inputs for the MSE simulation function. Something similar is probably viable here, but there might be a nicer way to do this...

**Comment by chengmatt** [comment]
I do it the old fashioned way where I have an excel spreadsheet of variables I want to change, after which I call them in through R... but I think expand.grid is probably better than that...

**Comment by Ovec8hkin** [comment]
Will probably make a function `run_mse_multiple(oms, hcrs, seeds, ...)` that accepts lists of OMs, HCRs, and simulation seeds, and creates a grid of combinations to run in parallel.

Will need to make a modification to how HCRs are defined in order to handle HCRs that include harvest caps and stability constraints.

**Comment by Ovec8hkin** [comment]
Closed by a99c2004f4bd448e4a0c2e83a6aa1b4e953309b8
